### ISSUE TITLE
Using AWSGoat and CICDGoat together

### ISSUE THREAD

**Issue by Cyb3r-Monk** [ine-labs/AWSGoat#22]
Would it be possible to integrate AWSGoat with [CICDGoat](https://github.com/cider-security-research/cicd-goat)? The idea is to have a full pipeline for infrastructure as code and software development lifecycle. This way it would be possible to perform more simulations for example intentionally leaving an access key somewhere like web.config and pushing the changes to the main repo, building the web app and publishing it.

**Comment by nishantsharmax** [comment]
@gvndkrishna check feasibility
