### ISSUE TITLE
Running from actions is giving me errors with depreceated commands

### ISSUE THREAD

**Issue by 0xSebin** [ine-labs/AWSGoat#46]
![image](https://github.com/ine-labs/AWSGoat/assets/56429311/6d693505-5362-460d-8973-5d9d9c7594c0)

**Comment by 0xSebin** [comment]
Can anyone help>

**Comment by SSKale1** [comment]
@0xSebin We tested the deployments and the Terraform Apply/Destroy action does work without any issues, with the Application URL output too. These warnings for deprecation will be handled in a future update. 
If you've faced any other issues while deploying please share the error log for it.
