### ISSUE TITLE
There is something wrong in the backend server while logging/signing in

### ISSUE THREAD

**Issue by AlienwareSec** [ine-labs/AWSGoat#61]
![Screenshot_6](https://github.com/ine-labs/AWSGoat/assets/122386120/1c07f9cf-c9f2-4fea-bcd0-d13d904626a4)

**Comment by Rishappreet-Singh** [comment]
Hi AlienwareSec,

Thank you for raising this issue.

After reviewing the matter, everything appears to be functioning correctly. To gain a better understanding of the issue you are experiencing, could you please check the **GitHub Actions logs** for any errors? Additionally, when attempting to log in to the website, please examine the **CloudWatch logs** for the backend function ( **blog-application-data** ), which is located in **AWS Lambda** in the **us-east-1** region.

Your assistance with this will greatly help us in diagnosing and resolving the issue promptly.

Thank you for your cooperation.

Best regards,  
Rishappreet Singh Moonga


<img width="1292" alt="Aws Goat Login Screenshot" src="https://github.com/ine-labs/AWSGoat/assets/63499257/e765c5f9-537e-4eba-9bf9-bf63aefa2a8d">
