### ISSUE TITLE
Security Warning on created `policy.json`

### ISSUE THREAD

**Issue by za** [ine-labs/AWSGoat#66]
![Screenshot 2024-09-24 134121](https://github.com/user-attachments/assets/682c0d4c-5722-430e-aca9-1e8fc39fdc6d)

Hi there, 

while trying to create a new policy from `policy.json` (refer to this PR https://github.com/ine-labs/AWSGoat/pull/60), I found a security warning is being shown.

cc: @Rishappreet-Singh

**Comment by za** [comment]
Another one is `WARNING`:

![Screenshot 2024-09-24 171757](https://github.com/user-attachments/assets/12f7bd5d-d177-4107-888b-cb8d4be91f06)

**Comment by za** [comment]
Hi @Rishappreet-Singh any response? cc: @nishantsharmax

**Comment by Rishappreet-Singh** [comment]
Hi @za ,

I’ve reviewed the updated JSON, and it looks good for Module 1. However, with this change, Module 2 won’t be functional. Could you please also update your changes to include the policy.json file, so we can ensure everything works as expected.

**Update/Addition in policy.json**
```
{
    "Effect": "Allow",
    "Action": "iam:PassRole",
    "Resource": [
        "arn:aws:iam::*:role/AWS_GOAT_ROLE",
        "arn:aws:iam::*:role/blog_app_lambda*",
        "arn:aws:iam::*:role/ec2Deployer-role",
        "arn:aws:iam::*:role/ecs-instance-role",
        "arn:aws:iam::*:role/ecs-task-role"
    ]
},
{
    "Effect": "Allow",
    "Action": "iam:CreateServiceLinkedRole",
    "Resource": "*",
    "Condition": {
        "StringEquals": {
            "iam:AWSServiceName": [
                "autoscaling.amazonaws.com",
                "ecs.amazonaws.com",
                "elasticloadbalancing.amazonaws.com",
                "rds.amazonaws.com"
            ]
        }
    }
}
```

As for your earlier question about how I determined the minimum permissions, I did it mostly manually. I didn’t use any specific tools but instead gathered insights from AWS CloudTrail and then created the policy.json based on that.

Apologies for the delayed response, and Thank you again for your contribution!

**Comment by za** [comment]
BTW @Rishappreet-Singh how did we generated this `policy.json`? Do you know how?

**Comment by Rishappreet-Singh** [comment]
hey @za 

As mentioned in my previous comment, I got an idea of the necessary permissions using AWS CloudTrail. Alternatively, you can also check the "Last Accessed" information in the IAM user (the one used to deploy Terraform). From there, you can proceed by adding permissions and manually testing to ensure everything works as expected.

Hope this helps!

**Comment by za** [comment]
> hey @za
> 
> As mentioned in my previous comment, I got an idea of the necessary permissions using AWS CloudTrail. 

Ah sorry, I missed this. Noted @Rishappreet-Singh 📝

**Comment by za** [comment]
> Hi @za ,
> 
> I’ve reviewed the updated JSON, and it looks good for Module 1. However, with this change, Module 2 won’t be functional. Could you please also update your changes to include the policy.json file, so we can ensure everything works as expected.

OK, please wait while I am updating my PR @Rishappreet-Singh .

**Comment by za** [comment]
Ping @Rishappreet-Singh

**Comment by Rishappreet-Singh** [comment]
Hi @za,
 
I have reviewed the code, and everything looks good. We will proceed with merging it next week.

Thanks again for your contribution!

Best regards,
Rishappreet Singh
