### ISSUE TITLE
Deprecated resources

### ISSUE THREAD

**Issue by jesayafn** [ine-labs/AWSGoat#69]
I have discovered deprecated resources.
![image](https://github.com/user-attachments/assets/3fd9167c-eadd-4fd2-956f-4cdead7bdbef)
![image](https://github.com/user-attachments/assets/d94e118c-9f08-433f-bb74-bc3f916bccc3)

**Comment by za** [comment]
Ping @Rishappreet-Singh Any comment/feedback? cc: @nishantsharmax
