### ISSUE TITLE
Missing ID on terraform apply workflow

### ISSUE THREAD

**Issue by maximiliarthur** [ine-labs/AWSGoat#8]
I think there is a missing ID on line https://github.com/ine-labs/AWSGoat/blob/master/.github/workflows/tf-apply-main.yml#L41

Supposed to be like this:

```
    - name: Terraform Plan
      id: plan
      run: | 
        terraform plan -input=false
        ls -al
      continue-on-error: false
```
References
https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context

**Comment by jeswinMathai** [comment]
Thanks for pointing this out, we have refactored the workflow file and included a few more checks.
