### ISSUE TITLE
tf apply & destroy & apply will have issues next time around regarding API_GATEWAY_URL

### ISSUE THREAD

**Issue by mathiasconradt** [ine-labs/AWSGoat#9]
I tried the manual installation (not via Github action) and it works fine, however, when you **destroy** the same project and **re-apply** it again, the frontend will point to the wrong (old / previous) API_GATEWAY_URL, as it has already been replaced in the first run, due to:

```
main.tf:
3624: sed -i "s,API_GATEWAY_URL,${aws_api_gateway_deployment.apideploy_ba.invoke_url},g" modules/module-1/resources/s3/webfiles/build/static/js/main.5e35cae6.js
3625: sed -i "s,API_GATEWAY_URL,${aws_api_gateway_deployment.apideploy_ba.invoke_url},g" modules/module-1/resources/s3/webfiles/build/static/js/main.5e35cae6.js.map
```
Just mentioning it here in case others are wondering about the same. Feel free to close if it's not intended to be used like this (destroyed and re-applie).

![image](https://user-images.githubusercontent.com/295122/184473939-9a1747d6-3ed5-48f1-8af2-abc1880c9407.png)

**Comment by jeswinMathai** [comment]
Thanks, Mathias, for pointing this out. We have updated the terraform script to handle the redeployment of the project. #12
